drop table if exists number cascade;

create table number(
    id int8 generated by default as identity,
    found boolean,
    latency int8,
    number int8,
    text varchar(255),
    primary key (id)
 );
